services:
  - type: web
    name: semantic-validation-api
    env: docker
    plan: starter
    region: oregon
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8080
    buildCommand: docker build -t semantic-validation-api .
    startCommand: docker run -p $PORT:8080 semantic-validation-api
