services:
  - type: web
    name: semantic-validation-api
    env: docker
    region: oregon  # US West
    plan: starter
    dockerfilePath: ./Dockerfile  # Root directory
    dockerContext: .
    healthCheckPath: /health  # Match our FastAPI endpoint
    envVars:
      - key: PORT
        value: 8080
    buildCommand: docker build -t semantic-validation-api .
    startCommand: docker run -p $PORT:8080 semantic-validation-api
