services:
  - type: web
    name: semantic-validation-api
    env: docker
    buildCommand: docker build -t semantic-validation-api .
    startCommand: docker run -p 8080:8080 semantic-validation-api
