services:
  - type: web
    name: semantic-validation-api
    env: docker
    region: us-west-1
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8080
    dockerfilePath: ./Dockerfile
    dockerContext: ./
