services:
  - type: web
    name: semantic-validation-api
    env: docker
    region: oregon
    plan: starter
    dockerfilePath: Dockerfile
    dockerContext: /
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8080
    buildCommand: docker build -t semantic-validation-api /opt/render/project/src
    startCommand: docker run -p $PORT:8080 semantic-validation-api
