# Model configurations
models:
  default: "all-MiniLM-L6-v2"      # General purpose embedding model
  clinical: "pritamdeka/Bio_ClinicalBERT"  # Medical domain-specific model
  multilingual: "paraphrase-multilingual-MiniLM-L12-v2"  # Support for multiple languages

# Similarity thresholds for different comparison types
thresholds:
  default: 0.75       # Default threshold for basic comparison
  strict: 0.85        # High threshold for strict matching
  lenient: 0.65       # Lower threshold for more flexible matching
  medical: 0.80       # Specific threshold for medical text comparison

# Domain-specific modules and their thresholds
modules:
  diagnosis:
    AMA: 0.80         # Accuracy of Medical Assessment
    AI-MPN: 0.85      # Alignment with Physician Notes
  treatment:
    TDBE: 0.75        # Treatment Description Basic Elements
    SMCC: 0.70        # Synthesized Medical Care Comparison
  humanization:
    ICSE: 0.65        # Interpersonal Communication Style Equivalence
    OIFC: 0.60        # Overall Information Fidelity Check

# Text preprocessing options
preprocessing:
  remove_punctuation: true
  lowercase: true
  remove_stopwords: false
  normalize_whitespace: true
  stemming: false
  
  # Medical term normalization
  normalize_medical_terms: true
  medical_abbreviations:
    "temp": "temperature"
    "BP": "blood pressure"
    "HR": "heart rate"
    "O2": "oxygen"
    "RR": "respiratory rate"
    "Hx": "history"
    "Dx": "diagnosis"
    "Tx": "treatment"

